# PVC and PV
# What do want?
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-pvc
spec:
  storageClassName: mssql-cloud-ssd
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# How do we want it implemented
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mssql-cloud-ssd
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql-db
spec:
  selector:
    matchLabels:
      app: mssql-db
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: mssql-db
    spec:
      containers:
      - name: mssql-db
        image: mcr.microsoft.com/mssql/server:2019-latest
        resources:
          requests:
            cpu: 500m
            memory: 2000M

        env:
          - name: MSSQL_PID
            value: "Standard"
          - name: ACCEPT_EULA
            value: "Y"
          - name: MSSQL_SA_PASSWORD
            valueFrom:
              secretKeyRef:
                name: user-pass
                key: sapassword
        volumeMounts:
          - name: db-persistent-storage
            mountPath: /var/opt/mssql
      initContainers:
      - name: mssql-change-owner
        image: busybox:latest
        command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/opt/mssql
      volumes:
        - name: db-persistent-storage
          # pointer to the configuration of HOW we want the mount to be implemented
          persistentVolumeClaim:
            claimName: mssql-pvc

---
kind: Service
apiVersion: v1
metadata:
  name: mssql-db
spec:
  selector:
    app: mssql-db
  ports:
    - name: mssql-port
      port: 1433
      targetPort: 1433
  type: LoadBalancer
